// GENERATED by scripts/gen_ui_contract.py from core/core-api.yaml v3.2.0 — do not edit.
// The wire contract of the operations the staff console proxies.

export interface Entity {
  address?: string | null;
  address_change?: string | null;
  address_new?: string | null;
  address_previous?: string | null;
  contact?: string | null;
  contact_preference?: string | null;
  date_of_birth?: string | null;
  disabled?: string | null;
  email?: string | null;
  esign_consent?: string | null;
  id?: string | null;
  jurisdiction?: string | null;
  name?: string | null;
  reg_e_opt_in?: string | null;
  status?: "pending" | "active" | "disabled" | "archived" | null;
  tin?: string | null;
  type?: string | null;
  update?: string | null;
  blnk_identity_id?: string | null;
  created_at?: string | null;
  owners?: Record<string, unknown> | null;
  partner_id?: string | null;
  updated_at?: string | null;
}

export interface Account {
  account_type?: "checking" | "share_draft" | "share" | "money_market" | "share_certificate" | "ira" | "keogh" | null;
  balance?: number | null;
  blnk_ledger_id?: string | null;
  created_at?: string | null;
  id?: string | null;
  lock_type?: "none" | "compliance" | "fraud" | "legal" | "admin" | "deceased" | "expelled" | null;
  maturity_date?: string | null;
  maturity_disposition?: string | null;
  opening_channel?: string | null;
  status?: "open" | "frozen" | "closed" | null;
  closure_payout_due_at?: string | null;
  maturity_notice_due_at?: string | null;
  adverse_action?: string | null;
  death_flag?: boolean | null;
  maturity_window?: string | null;
  restriction?: string | null;
  active_freeze_count?: number | null;
  balance_synced_at?: string | null;
  blnk_balance_id?: string | null;
  credits_blocked?: boolean | null;
  debits_blocked?: boolean | null;
  entity_id?: string | null;
  partner_id?: string | null;
  updated_at?: string | null;
}

export interface Transfer {
  beneficiary?: unknown | null;
  id?: string | null;
  originator?: unknown | null;
  status?: "pending_approval" | "submitted" | "settled" | "returned" | "rejected" | "canceled" | null;
  amount_cents?: number | null;
  blnk_reference?: string | null;
  blnk_status?: string | null;
  blnk_transaction_id?: string | null;
  counterparty?: Record<string, unknown> | null;
  created_at?: string | null;
  partner_id?: string | null;
  synced_at?: string | null;
  updated_at?: string | null;
}

export interface Pagination {
  has_more?: boolean | null;
  next_after?: string | null;
  limit?: number | null;
}

export interface Page<T> {
  data: T[];
  pagination: Pagination;
}
