#!/usr/bin/env python3
"""
factor_task_types.py — factor the 337-value Task.type enum into two dimensions.

Problem (surfaced by the enum-cardinality harness term): Task.type was a 337-value enum of
<subject>_<verb> cross-products, contradicting the architecture's generic-verb principle and
costing 650 in complexity. No control cites a specific task code (verified), so the collapse is
pure-win, zero policy churn.

This rewrites the data model into the two genuine dimensions:
  * Task.type    -> a bounded GENERIC VERB enum (task-vocab.yaml `verbs`), kept in sync with x-task-types.
  * Task.subject -> a free-form string carrying the noun (NOT an enum, so it never re-bloats the surface).

Deterministic given task-vocab.yaml (the only judgment-bearing input). For each frozen legacy code
(task-types-legacy.json): tokenize on _ and . ; the verb is the rightmost token whose canonical form
(via aliases) is in `verbs`; cadence tokens are dropped; remaining tokens are the subject ("general"
if empty). Codes with no verb token are REPORTED as unmapped — never force-assigned.

Outputs: rewrites core-api.yaml (Task.type enum + Task.subject + x-task-types) and writes a committed
task-type-map.json (legacy code -> {type, subject, confidence}) as the auditable reference / migration
key. Run author_contracts.py afterward so the /tasks contract body picks up the new small enum.
"""
from __future__ import annotations
import json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
import yaml
SPEC = os.path.join(REPO, "core-api.yaml")
VOCAB = os.path.join(HERE, "task-vocab.yaml")
LEGACY = os.path.join(HERE, "task-types-legacy.json")
MAP_OUT = os.path.join(HERE, "task-type-map.json")
DUMP = dict(sort_keys=False, default_flow_style=False, width=120, allow_unicode=True)


def factor(code: str, verbs: set, aliases: dict, cadence: set):
    """Return (verb, subject, confidence). Verb-less codes fall to ('other', <code>, 'unmapped')
    so no legacy code is lost — its full name is preserved as the subject for later human triage."""
    toks = re.split(r"[._]", code)
    canon = [aliases.get(t, t) for t in toks]
    # rightmost token that canonicalizes to a known verb
    verb_idx = next((i for i in range(len(canon) - 1, -1, -1) if canon[i] in verbs), None)
    if verb_idx is None:
        return "other", code, "unmapped"
    verb = canon[verb_idx]
    # subject = every token except the matched verb and pure cadence modifiers. Other noun tokens
    # are kept even if they coincide with a verb word (e.g. "audit" in audit_assessment_annual).
    subj_toks = [t for i, t in enumerate(toks) if i != verb_idx and t not in cadence]
    subject = "_".join(subj_toks) or "general"
    # confidence: high when the verb was the trailing token (the common subject_verb shape)
    confidence = "high" if verb_idx == len(toks) - 1 else "derived"
    return verb, subject, confidence


def main() -> int:
    vocab = yaml.safe_load(open(VOCAB).read())
    verbs = set(vocab["verbs"]); aliases = dict(vocab.get("aliases") or {}); cadence = set(vocab.get("cadence") or [])
    legacy = sorted(json.load(open(LEGACY))["codes"])

    mapping, unmapped, used_verbs = {}, [], set()
    for code in legacy:
        v, s, conf = factor(code, verbs, aliases, cadence)
        mapping[code] = {"type": v, "subject": s, "confidence": conf}
        used_verbs.add(v)
        if conf == "unmapped":
            unmapped.append(code)

    # write the auditable map
    json.dump({"_note": "Legacy Task.type code -> factored {type (generic verb), subject (noun)}. "
               "Generated by factor_task_types.py from task-vocab.yaml + task-types-legacy.json. "
               "Auditable reference + migration key; the spec carries only the two dimensions.",
               "verbs_used": sorted(used_verbs), "unmapped": unmapped,
               "map": mapping}, open(MAP_OUT, "w"), indent=2)

    # rewrite the schema ('other' is the honest catch-all for verb-less legacy codes)
    doc = yaml.safe_load(open(SPEC).read())
    final_verbs = sorted(verbs | {"other"})

    # Guard: the spec's existing task tokens reference the current x-task-types directly, so the
    # new verb set MUST be a superset — aliasing one away (e.g. purge -> disposal) would orphan
    # those tokens (parse_core_api emits "unregistered task_type" warnings). Fail loudly instead.
    prev = set(doc.get("x-task-types") or [])
    missing = prev - set(final_verbs)
    if missing:
        sys.exit(f"factor_task_types: refusing to drop existing task verbs {sorted(missing)} — "
                 f"add them to task-vocab.yaml `verbs` (do not alias an existing verb away).")
    task = doc["components"]["schemas"]["Task"]["properties"]
    task["type"] = {"type": "string", "enum": final_verbs,
                    "description": "Generic task verb. The task's noun/domain is carried in `subject`."}
    # insert subject right after type, preserving order
    props = doc["components"]["schemas"]["Task"]["properties"]
    if "subject" not in props:
        rebuilt = {}
        for k, val in props.items():
            rebuilt[k] = val
            if k == "type":
                rebuilt["subject"] = {"type": "string",
                                      "description": "What the task concerns (noun/domain), e.g. access, vendor, "
                                                     "hmda_lar. Free-form; see task-type-map.json for the legacy keys."}
        doc["components"]["schemas"]["Task"]["properties"] = rebuilt
    doc["x-task-types"] = final_verbs

    open(SPEC, "w").write(yaml.safe_dump(doc, **DUMP))
    cov = len(mapping)
    print(f"factored {cov}/{len(legacy)} legacy codes ({100*cov//len(legacy)}%) into "
          f"{len(final_verbs)} generic verbs + a subject string")
    print(f"  verbs actually used: {len(used_verbs)} | enum overage vs cap 12: {max(0, len(final_verbs)-12)}")
    if unmapped:
        print(f"  UNMAPPED ({len(unmapped)}) — no verb token, left for review: {unmapped}")
    print(f"  wrote {os.path.relpath(MAP_OUT, REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
