#!/usr/bin/env python3
"""Generate the staff console's core-API contract from the spec.

Two outputs, both derived from core/core-api.yaml:

  ui/src/lib/coreApi.allowlist.json
      The proxy's path + query-param allowlist, from every GET operation
      marked `x-ui-surface: true`. The deliberate "what may the browser
      reach" line now lives in the SPEC; the UI file is a build artifact.

  ui/src/lib/core-api-types.d.ts
      TypeScript interfaces for the resource schemas the console renders,
      so editors and `tsc --checkJs` can hold the UI to the wire contract.

  python3 scripts/gen_ui_contract.py            # write both
  python3 scripts/gen_ui_contract.py --check    # exit 1 if either is stale
"""
import argparse
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import yaml  # noqa: E402
import spec_io  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "core" / "core-api.yaml"
ALLOWLIST = ROOT / "ui" / "src" / "lib" / "coreApi.allowlist.json"
TYPES = ROOT / "ui" / "src" / "lib" / "core-api-types.d.ts"

# resource schemas the console renders (list envelopes are structural)
UI_SCHEMAS = ["Entity", "Account", "Transfer", "Pagination"]

TS_TYPE = {"string": "string", "integer": "number", "number": "number",
           "boolean": "boolean", "object": "Record<string, unknown>",
           "array": "unknown[]"}


def build_allowlist(doc):
    paths, params = [], set()
    for p, methods in sorted((doc.get("paths") or {}).items()):
        op = (methods or {}).get("get")
        if not op or not op.get("x-ui-surface"):
            continue
        # escape literal segments — an unescaped '.' or '+' in a future path
        # would silently widen a SECURITY allowlist into a wildcard
        segments = re.split(r"\{[^}]+\}", p.lstrip("/"))
        pat = "^" + "[A-Za-z0-9_-]+".join(re.escape(s) for s in segments) + "$"
        paths.append({"path": p, "pattern": pat})
        for pr in op.get("parameters") or []:
            if isinstance(pr, dict) and pr.get("in") == "query":
                params.add(pr["name"])
            elif isinstance(pr, dict) and "$ref" in pr:
                # components/parameters refs (Limit/After) are query params
                name = pr["$ref"].rsplit("/", 1)[-1].lower()
                params.add({"limit": "limit", "after": "after"}.get(name, name))
    return {
        "_generated": "scripts/gen_ui_contract.py — from core-api.yaml "
                      "x-ui-surface operations. Do not edit; edit the spec.",
        "paths": paths,
        "params": sorted(params),
    }


def ts_interface(name, schema, all_schemas):
    props = dict(schema.get("properties") or {})
    for item in schema.get("allOf") or []:
        if isinstance(item, dict) and "$ref" in item:
            base = all_schemas.get(item["$ref"].rsplit("/", 1)[-1]) or {}
            for k, v in (base.get("properties") or {}).items():
                props.setdefault(k, v)
        for k, v in (item.get("properties") or {}).items() if isinstance(item, dict) else []:
            props.setdefault(k, v)
    lines = [f"export interface {name} {{"]
    for pn, ps in props.items():
        if not isinstance(ps, dict):
            ps = {}
        if ps.get("enum"):
            t = " | ".join(json.dumps(v) for v in ps["enum"])
        else:
            t = TS_TYPE.get(ps.get("type"), "unknown")
        lines.append(f"  {pn}?: {t} | null;")
    lines.append("}")
    return "\n".join(lines)


def build_types(doc):
    schemas = (doc.get("components") or {}).get("schemas") or {}
    out = ["// GENERATED by scripts/gen_ui_contract.py from core/core-api.yaml "
           f"v{doc.get('info', {}).get('version', '?')} — do not edit.",
           "// The wire contract of the operations the staff console proxies.", ""]
    for name in UI_SCHEMAS:
        if name in schemas:
            out.append(ts_interface(name, schemas[name], schemas))
            out.append("")
    out.append("export interface Page<T> {")
    out.append("  data: T[];")
    out.append("  pagination: Pagination;")
    out.append("}")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    doc = spec_io.load_spec(SPEC)
    allowlist = build_allowlist(doc)
    allow = json.dumps(allowlist, indent=2) + "\n"
    types = build_types(doc)

    import generated
    outputs = {ALLOWLIST: allow, TYPES: types}
    if args.check:
        if generated.check_or_write(outputs, check=True,
                                    rerun_hint="scripts/gen_ui_contract.py"):
            return 1
        print("ui contract OK — allowlist and types match the spec.")
        return 0

    generated.check_or_write(outputs, check=False, rerun_hint="")
    print(f"wrote {ALLOWLIST.name} ({len(allowlist['paths'])} paths) and {TYPES.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
