#!/usr/bin/env python3
"""Generate docs/proposed-surface.md — the designed-but-unimplemented API.

`x-proposed-paths` is the spec's parking lot: operations that were designed
(mostly by the core-api-loop from accumulated policy demand) but have no
route, no handler, and are deliberately excluded from route parity. Until
this page existed, nothing summarized that surface anywhere — TODO.md §4
called it out as the largest undocumented gap.

Groups operations by top-level resource and cross-references two demand
signals: whether the verifier holds a `spec_ahead` state-machine target for
the resource, and whether a schema for it already exists in
components/schemas. Regenerated by scripts/rebuild_artifacts.sh; do not edit
the output by hand.
"""
import collections
import json
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "core" / "core-api.yaml"
TARGETS = ROOT / "core" / "verifier" / "targets.json"
OUT = ROOT / "docs" / "proposed-surface.md"

METHODS = ("get", "post", "put", "patch", "delete")


def main():
    spec = yaml.safe_load(SPEC.read_text())
    proposed = spec.get("x-proposed-paths") or {}
    schemas = set((spec.get("components") or {}).get("schemas") or {})

    targets = json.loads(TARGETS.read_text()).get("targets", [])
    def norm(s):
        # CamelCase / snake_case -> lowercase alpha only, singular-ish
        return "".join(c for c in str(s).lower() if c.isalpha())

    sm_ahead = {
        norm(t.get("payload", {}).get("resource", ""))
        for t in targets
        if t.get("kind") == "state_machine" and t.get("status") == "spec_ahead"
    }

    groups = collections.defaultdict(list)
    n_ops = 0
    for path, item in sorted(proposed.items()):
        seg = path.strip("/").split("/")[0]
        for m in METHODS:
            op = item.get(m)
            if not isinstance(op, dict):
                continue
            groups[seg].append((m.upper(), path, str(op.get("summary") or "").strip()))
            n_ops += 1

    lines = [
        "# The proposed surface — designed, not yet implemented",
        "",
        "> GENERATED by `scripts/gen_proposed_surface.py` (runs in",
        "> `scripts/rebuild_artifacts.sh`). Do not edit by hand.",
        ">",
        "> These operations live in `core/core-api.yaml`'s `x-proposed-paths`",
        "> block: designed — mostly by `core/core-api-loop/` from accumulated",
        "> policy demand — but with **no route and no handler**, and excluded",
        "> from route parity on purpose. An operation graduates by moving to",
        "> `paths:` with an `x-handler` and an implementation (the workflow is",
        "> in `CLAUDE.md`). Lending-adjacent entries stay parked by the",
        "> narrow-bank decision recorded in `api/index.ts`.",
        "",
        f"**{n_ops} operations across {len(groups)} resources.**",
        "",
        "| resource | ops | schema exists | verifier waits on it |",
        "|---|---|---|---|",
    ]
    schema_norms = {norm(s) for s in schemas}
    for seg in sorted(groups):
        ops = groups[seg]
        singular = norm(seg[:-1] if seg.endswith("s") else seg)
        has_schema = singular in schema_norms or norm(seg) in schema_norms
        waiting = "yes" if singular in sm_ahead else ""
        lines.append(
            f"| `/{seg}` | {len(ops)} | {'yes' if has_schema else ''} | {waiting} |"
        )

    lines += ["", "## Operations by resource", ""]
    for seg in sorted(groups):
        lines.append(f"### /{seg}")
        lines.append("")
        for m, path, summary in groups[seg]:
            desc = f" — {summary}" if summary and not summary.startswith(m) else ""
            lines.append(f"- `{m} {path}`{desc}")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} — {n_ops} proposed operations, {len(groups)} resources")


if __name__ == "__main__":
    main()
