#!/usr/bin/env python3
"""Generate the router's route table from the spec.

Since 2026-08 the spec's paths section is the canonical API surface (parity-
gated). This generator completes the inversion: every operation that names a
concrete handler (x-handler: "module.function") becomes a Route entry in
core/supabase/functions/api/routes.gen.ts, and index.ts merely spreads the
generated array after its two hand-written chrome routes (x-handler:
"index.ts (inline)").

A new endpoint therefore STARTS in core-api.yaml: declare the operation with
x-handler / x-tier / x-actors / x-audience, rerun this, and the route exists —
with its authorization class enforced by route_gating.test.ts.

  python3 scripts/gen_routes.py            # write routes.gen.ts
  python3 scripts/gen_routes.py --check    # exit 1 if stale
"""
import argparse
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import yaml  # noqa: E402
import spec_io  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "core" / "core-api.yaml"
OUT = ROOT / "core" / "supabase" / "functions" / "api" / "routes.gen.ts"

HEADER = """\
// GENERATED by scripts/gen_routes.py from core/core-api.yaml — do not edit.
//
// The spec's paths section is the canonical API surface (route parity and
// route-gating tests enforce it). Each operation's x-handler names the
// implementation; x-tier / x-actors / x-audience carry its authorization
// class. Add or change an endpoint by editing the SPEC, then rerun the
// generator. index.ts spreads this array after its inline chrome routes.
import { createDb } from "./lib.ts";
import { type Route } from "./auth.ts";
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    doc = spec_io.load_spec(SPEC)
    by_module: dict[str, set] = {}
    entries = []
    for path in sorted(doc.get("paths") or {}):
        for method, op in sorted((doc["paths"][path] or {}).items()):
            handler = op.get("x-handler", "")
            if "." not in handler or handler.startswith("index.ts"):
                continue
            if op.get("x-route") == "hand":
                # bespoke wiring (Blnk config injection, non-standard arg
                # order) — the entry stays hand-written in index.ts
                continue
            module, fn = handler.split(".", 1)
            by_module.setdefault(module, set()).add(fn)
            params = re.findall(r"\{([^}]+)\}", path)
            pattern = "^" + re.sub(r"\{[^}]+\}", "([^/]+)",
                                   path).replace("/", r"\/") + r"\/?$"
            actors = op.get("x-actors")
            public = op.get("x-audience") == "public"
            lines = ["  {",
                     f'    method: "{method.upper()}", pattern: /{pattern}/,',
                     f'    endpoint: "{method.upper()} {path}", '
                     f'tier: "{op.get("x-tier", "write")}", '
                     f"paramNames: [{', '.join(json.dumps(p) for p in params)}],"]
            if actors:
                lines.append(f"    actors: [{', '.join(json.dumps(a) for a in actors)}],")
            if public:
                lines.append("    public: true,")
            audience = op.get("x-audience")
            if audience:
                lines.append(f"    audience: {json.dumps(audience)},")
            if params:
                args_ts = ", ".join(f"params.{p}" for p in params)
                lines.append("    handler: async (req, params, requestId, ctx) =>")
                lines.append(f"      await {fn}(req, {args_ts}, createDb(), requestId, ctx),")
            else:
                lines.append("    handler: async (req, _params, requestId, ctx) =>")
                lines.append(f"      await {fn}(req, createDb(), requestId, ctx),")
            lines.append("  },")
            entries.append("\n".join(lines))

    imports = []
    for module in sorted(by_module):
        names = ", ".join(sorted(by_module[module]))
        block = f"import {{ {names} }} from \"./{module}.ts\";"
        if len(block) > 100:
            block = ("import {\n  " + ",\n  ".join(sorted(by_module[module]))
                     + ",\n} from \"./" + module + ".ts\";")
        imports.append(block)

    text = (HEADER + "\n".join(imports)
            + "\n\nexport const generatedRoutes: Route[] = [\n"
            + "\n".join(entries) + "\n];\n")

    import generated
    if args.check:
        if generated.check_or_write({OUT: text}, check=True,
                                    rerun_hint="scripts/gen_routes.py"):
            return 1
        print(f"routes.gen.ts OK — {len(entries)} generated routes match the spec.")
        return 0

    generated.check_or_write({OUT: text}, check=False, rerun_hint="")
    print(f"wrote routes.gen.ts — {len(entries)} routes from "
          f"{len(by_module)} modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
