#!/usr/bin/env python3
"""Generate STATE.md — the one page of live numbers.

Every count a hand-written doc is tempted to embed lives here instead,
derived from the same artifacts the gates already trust. Prose docs link to
STATE.md; scripts/check_doc_claims.py fails the build when a doc embeds a
number that disagrees with the artifacts. Run via scripts/rebuild_artifacts.sh
(after every generator, so it reads the fresh outputs).

Also exports state() for check_doc_claims.py, so the checker and the page
can never disagree about what the true numbers are.
"""

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "STATE.md"


def _load(rel):
    return json.load((ROOT / rel).open())


def state():
    """Every number STATE.md prints, keyed for reuse by the claims checker."""
    vocab = _load("core-vocabulary.json")
    controls = _load("controls.json")
    hermetic = _load("control-tests.json")["summary"]
    live = _load("control-tests-live.json")["summary"]
    xwalk = _load("crosswalk.json")
    mappings = _load("crosswalk-mappings.json")
    targets = _load("core/verifier/targets.json")
    allowlist = _load("ui/src/lib/coreApi.allowlist.json")

    by_kind = {}
    ready = 0
    for t in targets["targets"]:
        by_kind[t["kind"]] = by_kind.get(t["kind"], 0) + 1
        if t.get("status") == "ready":
            ready += 1

    harness = ROOT / "core" / "supabase" / "tests" / "e2e" / "compliance_e2e.sh"
    e2e_checks = sum(
        1 for ln in harness.read_text().splitlines() if re.match(r"\s*check ", ln)
    )

    routes_ts = (ROOT / "core" / "supabase" / "functions" / "api" / "routes.gen.ts").read_text()
    routes = len(re.findall(r'method: "[A-Z]+"', routes_ts))

    api_dir = ROOT / "core" / "supabase" / "functions" / "api"
    modules = sum(
        1 for p in api_dir.glob("*.ts")
        if not p.name.endswith((".test.ts", ".gen.ts"))
    )

    migrations = sum(1 for _ in (ROOT / "core" / "supabase" / "migrations").glob("*.sql"))

    decisions_md = (ROOT / "core" / "architecture-decisions.md").read_text(errors="replace")
    decisions = len(set(re.findall(r"^###\s+Decision\s+(\d+):", decisions_md, re.MULTILINE)))

    policies = sorted({c["policy"] for c in controls["controls"]})
    prompts = sum(1 for _ in (ROOT / "compliance" / "policies").glob("*/prompt.md"))

    claims = [c for m in xwalk["mappings"]["mappings"] for c in m["claims"]]
    reach_counts = {}
    for row in xwalk["reachability"]:
        r = row["reachability"]
        reach_counts[r] = reach_counts.get(r, 0) + 1

    return {
        "spec_version": vocab["meta"]["spec_version"],
        "endpoints": len(vocab["endpoints"]),
        "events": len(vocab["events"]),
        "event_types": len(vocab["event_types"]),
        "migrations": migrations,
        "api_modules": modules,
        "routes": routes,
        "e2e_assertions": e2e_checks,
        "decisions": decisions,
        "policies": len(policies),
        "policy_prompts": prompts,
        "controls_total": hermetic["total"],
        "controls_in_scope": hermetic["in_scope"],
        "controls_scoped_out": hermetic["scoped_out"],
        "hermetic_green": hermetic["in_scope_green"],
        "hermetic_red": hermetic["in_scope_red"],
        "live_ran": live["ran"],
        "live_green": live["in_scope_green"],
        "live_red": live["in_scope_red"],
        "fake_vs_real": len(live["fake_vs_real_defects"]),
        "claims": len(claims),
        "claims_unreviewed": sum(1 for c in claims if c.get("needs_review")),
        "open_questions": len(mappings["open_questions"]),
        "reachable": reach_counts.get("reachable", 0),
        "partially_reachable": reach_counts.get("partially_reachable", 0),
        "unreachable": reach_counts.get("unreachable", 0),
        "targets_total": len(targets["targets"]),
        "targets_ready": ready,
        "targets_by_kind": by_kind,
        "ui_surface_paths": len(allowlist["paths"]),
    }


def render(s):
    k = s["targets_by_kind"]
    non_control = s["targets_total"] - k.get("control", 0)
    return f"""# STATE — the live numbers

> GENERATED by `scripts/gen_state.py` (runs in `scripts/rebuild_artifacts.sh`).
> Do not edit, and do not restate these numbers in hand-written prose — link
> here instead. `scripts/check_doc_claims.py` goes red when a doc disagrees.

## Spec (`core/core-api.yaml` v{s['spec_version']})

| | |
|---|---|
| endpoints | {s['endpoints']} |
| routed operations (`routes.gen.ts`) | {s['routes']} |
| registered event codes | {s['events']} |
| canonical event types (`x-event-types`) | {s['event_types']} |
| UI-surface paths (proxy allowlist) | {s['ui_surface_paths']} |

## Core

| | |
|---|---|
| migrations | {s['migrations']} |
| API modules | {s['api_modules']} |
| e2e harness assertions (`check` calls) | {s['e2e_assertions']} |
| architecture decisions (D1–D{s['decisions']}) | {s['decisions']} |

## Compliance

| | |
|---|---|
| policies in the catalogue | {s['policies']} (of which {s['policy_prompts']} regenerable via `prompt.md`) |
| controls | {s['controls_total']} total — {s['controls_in_scope']} in scope, {s['controls_scoped_out']} scoped out |
| hermetic tier | {s['hermetic_green']} green / {s['hermetic_red']} red (in scope) |
| live tier | {s['live_green']} green / {s['live_red']} red (in scope), {s['fake_vs_real']} fake-vs-real defects |

## Crosswalk

| | |
|---|---|
| regulatory claims | {s['claims']} ({s['claims_unreviewed']} awaiting review) |
| open questions | {s['open_questions']} |
| reachability | {s['reachable']} reachable / {s['partially_reachable']} partial / {s['unreachable']} unreachable |

## Verifier

| | |
|---|---|
| targets | {s['targets_total']} ({s['targets_ready']} ready) |
| by kind | {k.get('contract', 0)} contract, {k.get('control', 0)} control, {k.get('property', 0)} property, {k.get('state_machine', 0)} state-machine |
| non-control (drill does not cover) | {non_control} |
"""


def main():
    OUT.write_text(render(state()))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
