#!/usr/bin/env python3
"""
journal.py — one human-readable place to see every hypothesis the loop tested and its outcome.

Merges, in chronological order:
  * inner-loop moves   — core-api-loop/moves.jsonl    (each spec edit run_loop.py adjudicated:
                          the move label is the hypothesis; kept/Δ/coverage/complexity the outcome)
  * outer-loop cycles  — core-api-loop/regen-log.jsonl (each policy regeneration measured by
                          regenerate.py: "regenerate <slug>" is the hypothesis; demand/unregistered
                          delta the outcome)

  python core-api-loop/journal.py            # print the table + summary
  python core-api-loop/journal.py --write     # also (re)write core-api-loop/JOURNAL.md
  python core-api-loop/journal.py --kept-only  # only the moves that were kept

These logs are local working state (gitignored); JOURNAL.md is a regenerable snapshot of them.
"""

from __future__ import annotations

import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
MOVES = os.path.join(HERE, "moves.jsonl")
REGEN = os.path.join(HERE, "regen-log.jsonl")
JOURNAL_MD = os.path.join(HERE, "JOURNAL.md")


def _load(path: str) -> list[dict]:
    if not os.path.exists(path):
        return []
    out = []
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if line:
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return out


def _ts(s: str | None) -> str:
    """Trim ISO timestamp to 'MM-DD HH:MM' for compact display."""
    if not s:
        return "?"
    return s.replace("T", " ")[5:16]


def _inner_outcome(r: dict) -> str:
    cov = r.get("coverage", {})
    head = "KEPT  " if r.get("kept") else "revert"
    delta = r.get("delta", 0)
    s = (f"{head} Δ{delta:+g} | unreg {cov.get('unregistered_codes', '?')} "
         f"arch {cov.get('uncovered_arch_elements', '?')} cx {r.get('complexity', '?')}")
    if r.get("kept") and r.get("commit"):
        s += f" [{r['commit']}]"
    return s


def _outer_outcome(r: dict) -> str:
    if "unregistered_delta" in r:
        return (f"unreg {r['unregistered_before']}→{r['unregistered_after']} "
                f"({r['unregistered_delta']:+d}) | demand {r['demand_before']}→{r['demand_after']} "
                f"(+{r['codes_added']}/-{r['codes_removed']})")
    return (f"demand {r['demand_before']}→{r['demand_after']} "
            f"(+{r['codes_added']}/-{r['codes_removed']})")


def rows(kept_only: bool = False) -> list[dict]:
    out = []
    for r in _load(MOVES):
        if kept_only and not r.get("kept"):
            continue
        out.append({"ts": r.get("ts"), "loop": "inner",
                    "hypothesis": r.get("hypothesis") or r.get("label") or "(unlabeled)",
                    "note": r.get("note"), "outcome": _inner_outcome(r)})
    for r in _load(REGEN):
        out.append({"ts": r.get("ts"), "loop": "outer",
                    "hypothesis": r.get("hypothesis") or "(regenerate)",
                    "note": r.get("note"), "outcome": _outer_outcome(r)})
    out.sort(key=lambda x: x["ts"] or "")
    return out


def summary() -> dict:
    moves = _load(MOVES)
    regen = _load(REGEN)
    kept = [m for m in moves if m.get("kept")]
    best_first = next((m["best_score"] for m in moves), None)
    best_last = kept[-1]["candidate_score"] if kept else best_first
    return {
        "inner_moves": len(moves),
        "inner_kept": len(kept),
        "inner_reverted": len(moves) - len(kept),
        "best_score_start": best_first,
        "best_score_now": best_last,
        "outer_cycles": len(regen),
    }


def render_text(kept_only: bool = False) -> str:
    rs = rows(kept_only)
    lines = [f"{'TIME':<12} {'LOOP':<5} {'HYPOTHESIS':<46} OUTCOME"]
    lines.append("-" * 110)
    for r in rs:
        hyp = (r["hypothesis"] or "")[:46]
        lines.append(f"{_ts(r['ts']):<12} {r['loop']:<5} {hyp:<46} {r['outcome']}")
        if r["note"]:
            lines.append(f"{'':<12} {'':<5} note: {r['note']}")
    s = summary()
    lines.append("")
    lines.append(f"inner: {s['inner_kept']}/{s['inner_moves']} moves kept "
                 f"({s['inner_reverted']} reverted) | best score "
                 f"{s['best_score_start']} → {s['best_score_now']} | outer cycles: {s['outer_cycles']}")
    return "\n".join(lines)


def render_markdown(kept_only: bool = False) -> str:
    rs = rows(kept_only)
    s = summary()
    out = ["# core-api-loop journal",
           "",
           "Every hypothesis the loop tested and its outcome "
           "(inner = spec edits, outer = policy regenerations). "
           "Generated by `journal.py` from `moves.jsonl` + `regen-log.jsonl`.",
           "",
           f"**Inner:** {s['inner_kept']}/{s['inner_moves']} moves kept "
           f"({s['inner_reverted']} reverted) · best score {s['best_score_start']} → "
           f"{s['best_score_now']}  **Outer:** {s['outer_cycles']} cycles",
           "",
           "| Time | Loop | Hypothesis | Outcome | Note |",
           "|---|---|---|---|---|"]
    for r in rs:
        note = (r["note"] or "").replace("|", "\\|")
        hyp = (r["hypothesis"] or "").replace("|", "\\|")
        outcome = r["outcome"].replace("|", "\\|")
        out.append(f"| {_ts(r['ts'])} | {r['loop']} | {hyp} | {outcome} | {note} |")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--write", action="store_true", help="also (re)write core-api-loop/JOURNAL.md")
    ap.add_argument("--kept-only", action="store_true", help="only moves that were kept")
    ap.add_argument("--markdown", action="store_true", help="print Markdown instead of a table")
    args = ap.parse_args(argv)

    if not os.path.exists(MOVES) and not os.path.exists(REGEN):
        print("no journal yet — run run_loop.py adjudicate / regenerate.py cycle first "
              f"(expected {os.path.relpath(MOVES)} and/or {os.path.relpath(REGEN)}).")
        return 0

    print(render_markdown(args.kept_only) if args.markdown else render_text(args.kept_only))
    if args.write:
        with open(JOURNAL_MD, "w", encoding="utf-8") as fh:
            fh.write(render_markdown(args.kept_only))
        print(f"\nwrote {JOURNAL_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
